spring:
  application:
    name: itsm-boot
  datasource:
    url: jdbc:mariadb://localhost:3306/itsmdb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: itsm
    password: Itsm!2345
    driver-class-name: org.mariadb.jdbc.Driver

server:
  port: 8081

mybatis:
  mapper-locations: classpath:/mybatis/mappers/**/*.xml
  type-aliases-package: kr.go.smplatform.itsm

itsm:
  security:
    enforce-permissions: true
